routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('guest')->group(function(){
    Route::get('/', 'Auth\LoginController@showLogin')->name('login.show');
    Route::post('/', 'Auth\LoginController@login')->name('login');
});
Route::middleware('auth')->group(function(){
    Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    //company
    Route::get('/companies', 'CompanyController@index')->name('company.index');
    Route::resource('company', 'CompanyController')->except('index');

    //employees
    Route::get('/employees', 'EmployeeController@index')->name('employee.index');
    Route::resource('employee', 'EmployeeController')->except('index', 'show');

});

app/Models/Company.php
<?php

namespace App\Models;

use App\Mail\CompanyRegisteredMail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Mail;

class Company extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
        'email',
        'logo',
        'website',
    ];

    public function employees(){
        return $this->hasMany(Employee::class, 'company', 'id');
    }

    public function sendMail(){
        if($this->email){
            Mail::to($this->email)->send(new CompanyRegisteredMail($this));
            return true;
        }
        return false;
    }
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = [
        'first_name',
        'last_name',
        'company',
        'email',
        'phone',
    ];
    public function myCompany(){
        return $this->belongsTo(Company::class, 'company','id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use Illuminate\Http\Request;
use App\Http\Requests\AddCompanyRequest;
use Illuminate\Support\Facades\Storage;
use Session;
class CompanyController extends Controller
{
    private $company;
    public function __construct(Company $company){
        $this->company = $company;
    }
    public function index(){
        $companies = Company::paginate(config('data.paginate_per_page'));
        return view('company.index')->with([
            'companies' => $companies
        ]);
    }

    public function create(Request $request){
        return view('company.create');
    }

    public function store(AddCompanyRequest $request){
        $logo = '';
        $files=$request->file('logo');
        if($files){
            $fileName = $files->getClientOriginalName();
            $fileExtension = '.'.$files->getClientOriginalExtension();
            $logo = md5($fileName.microtime()).$fileExtension;
            Storage::disk('local')->putFileAs('public/company', $files, $logo);
        }
        $companyCreate = $this->company->create([
           'name' => $request->name,
           'email' => $request->email,
           'logo' => $logo,
            'website' => $request->website
        ]);
        $companyCreate->sendMail();
        if($companyCreate){
            return redirect()->to('/companies');
        }
        return redirect()->back();
    }

    public function edit(Request $request, Company $company){
        return view('company.edit')->with([
            'company' => $company
        ]);
    }

    public function update(AddCompanyRequest $request, Company $company){
        $logo = $company->logo;
        $files=$request->file('logo');
        if($files){
            $fileName = $files->getClientOriginalName();
            $fileExtension = '.'.$files->getClientOriginalExtension();
            $newLogo = md5($fileName.microtime()).$fileExtension;
            Storage::delete('public/company/'.$logo);
            $logo= $newLogo;
            Storage::disk('local')->putFileAs('public/company', $files, $logo);
        }
        $company->name = $request->name;
        $company->email = $request->email;
        $company->website = $request->website;
        $company->logo = $logo;
        $company->save();
        return redirect()->to('/companies');
    }

    public function show(Request $request, Company $company){
        return view('company.show')->with([
            'company' => $company
        ]);
    }

    public function destroy(Request $request, Company $company){
        $company->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AddEmployeeRequest;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    private $employee;
    public function __construct(Employee $employee){
        $this->employee = $employee;
    }
    public function index(){
        $employees = Employee::paginate(config('data.paginate_per_page'));
        return view('employee.index')->with([
            'employees' => $employees
        ]);
    }

    public function create(Request $request){
        $companies = Company::all();
        return view('employee.create')->with([
            'companies' => $companies
        ]);
    }

    public function store(AddEmployeeRequest $request){
        $employeeCreate = $this->employee->create([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'company' => $request->company,
            'email' => $request->email,
            'phone' => $request->phone,
        ]);
        if($employeeCreate){
            return redirect()->to('/employees');
        }
        return redirect()->back();
    }

    public function edit(Request $request, Employee $employee){
        $companies = Company::all();
        return view('employee.edit')->with([
            'employee' => $employee,
            'companies' => $companies
        ]);
    }

    public function update(AddEmployeeRequest $request, Employee $employee){
        $employee->first_name = $request->first_name;
        $employee->last_name = $request->last_name;
        $employee->email = $request->email;
        $employee->phone = $request->phone;
        $employee->company = $request->company;
        $employee->save();
        return redirect()->to('/employees');
    }

    public function destroy(Request $request, Employee $employee){
        $employee->delete();
        return redirect()->back();
    }
}

resources/views/company/_form.blade.php
<div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{(isset($company->name)? $company->name:old('name'))}}"/>
    @if($errors->has('name'))
        <span class="text-danger">{{ $errors->first('name') }}</span>
    @endif
</div>
<div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{(isset($company->email)? $company->email:old('email'))}}"/>
    @if($errors->has('email'))
        <span class="text-danger">{{ $errors->first('email') }}</span>
    @endif
</div>
<div class="mb-3">
    <label for="website" class="form-label">Website</label>
    <input type="text" class="form-control @error('website') is-invalid @enderror" name="website" value="{{(isset($company->website)? $company->website:old('website'))}}"/>
    @if($errors->has('website'))
        <span class="text-danger">{{ $errors->first('website') }}</span>
    @endif
</div>
<div class="mb-3">
    <label for="logo" class="form-label">Logo</label>
    <input class="form-control form-control-lg @error('logo') is-invalid @enderror" name="logo" type="file" onchange="loadFile(event)" id="logo">
    @if($errors->has('logo'))
        <span class="text-danger">{{ $errors->first('logo') }}</span>
    @endif
    <span class="text-muted">Minimum dimension 100 x 100</span>
    <div class="image">
        @if(isset($company->logo))
            <img id="output" alt="" width="100" height="100" src="{{asset('storage/company/'.$company->logo)}}"/>
        @endif
    </div>
</div>


<script>
    const loadFile = function(event) {
        const img = new Image()
        img.src = window.URL.createObjectURL(event.target.files[0]);
        img.onload = function(){
            let output = document.getElementById('output');
            if(output){
                output.src = img.src;
            }else{
                $('<img src="" id="output" width="100" height="100"/>').appendTo('.image');
                output = document.getElementById('output');
                output.src = img.src;
            }

        }
    };
</script>

resources/views/company/create.blade.php
@extends('layout.admin')
@section('content')
    <div class="m-auto card p-2">
        <div class="card-body">
            <h5 class="card-title">Add New Company</h5>
            <form method="post" action="{{ route('company.store') }}" enctype="multipart/form-data">
                @csrf
                @include('company._form')
                <div class="d-flex justify-content-between">
                    <a href="{{route('company.index')}}" class="btn btn-secondary">Back</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/company/edit.blade.php
@extends('layout.admin')
@section('content')
    <div class="m-auto card p-2">
        <div class="card-body">
            <h5 class="card-title">Update Company</h5>
            <form method="post" action="{{ route('company.update', $company->id) }}" enctype="multipart/form-data">
                {{method_field('put')}}
                @csrf
                @include('company._form')
                <div class="d-flex justify-content-between">
                    <a href="{{route('company.index')}}" class="btn btn-secondary">Back</a>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/company/index.blade.php
@extends('layout.admin')
@section('content')

    <div class="m-4">
        <div class="text-end">
            <a href="{{route('company.create')}}" class="btn btn-primary">Add New</a>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Company Name</th>
                <th scope="col">Email</th>
                <th scope="col">Website</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($companies as $company)
            <tr>
                <td>
                    <div>
                        @if($company->logo)
                            <img src="{{asset('storage/company/'.$company->logo)}}" width="100" height="100" class="rounded img-thumbnail" />
                        @endif
                            {{$company->name}}
                    </div>
                </td>
                <td>{{$company->email}}</td>
                <td>{{$company->website}}</td>
                <td>
                    <a href="{{route('company.show', $company->id)}}">show</a>
                    <a href="{{route('company.edit', $company->id)}}">edit</a>
                    <button class="btn btn-link" onclick="event.preventDefault();
                          document.getElementById('company-delete-'+{{$company->id}}).submit();">
                        Delete
                    </button>
                    <form id="{{'company-delete-'.$company->id}}" action="{{route('company.destroy', $company->id)}}" method="post" class="d-none">
                        {{method_field('delete')}}
                        @csrf
                    </form>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>
        {{$companies->links('vendor.pagination.bootstrap-4')}}
    </div>
@endsection

resources/views/company/show.blade.php
@extends('layout.admin')
@section('content')
    <div class="card w-1/2 m-auto">
        <div class="card-body">
            <h5 class="card-title">{{$company->name}}</h5>
            <p class="text-16 bold underline">Company Detail</p>
            <div class="border p-2">
                <p>Email: {{$company->email}}</p>
                <p>Website: {{$company->website}}</p>
                <p>
                    <span class="bold">Employees:</span>
                    <br>
                    @foreach($company->employees as $employee)
                        <span>Name: {{$employee->first_name.' '.$employee->last_name}}</span>
                        <br>
                        <span>Email: {{$employee->email}}</span>
                        <br>
                        <span>Phone: {{$employee->phone}}</span>
                        <br>
                    @endforeach
                </p>
            </div>
            <a href="{{route('company.index')}}" class="btn btn-secondary mt-2">Back</a>
        </div>
    </div>
@endsection

resources/views/dashboard.blade.php
@extends('layout.admin')
@section('content')
    <div>
        Dashboard
    </div>
@endsection

resources/views/employee/_form.blade.php
<div class="mb-3">
    <label for="first_name" class="form-label">First Name</label>
    <input type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{(isset($employee->first_name)? $employee->first_name:old('first_name'))}}"/>
    @if($errors->has('first_name'))
        <span class="text-danger">{{ $errors->first('first_name') }}</span>
    @endif
</div>
<div class="mb-3">
    <label for="last_name" class="form-label">Last Name</label>
    <input type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{(isset($employee->last_name)? $employee->last_name:old('last_name'))}}"/>
    @if($errors->has('last_name'))
        <span class="text-danger">{{ $errors->first('last_name') }}</span>
    @endif
</div>
<div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{(isset($employee->email)? $employee->email:old('email'))}}"/>
    @if($errors->has('email'))
        <span class="text-danger">{{ $errors->first('email') }}</span>
    @endif
</div>
<div class="mb-3">
    <label for="phone" class="form-label">Phone</label>
    <input type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{(isset($employee->phone)? $employee->phone:old('phone'))}}"/>
    @if($errors->has('phone'))
        <span class="text-danger">{{ $errors->first('phone') }}</span>
    @endif
</div>
<div class="mb-3">
    <label class="col-md-12 col-form-label">Company</label>
    <select class="form-control  @error('company') is-invalid @enderror" name="company">
        <option value="">Select Company</option>
        @foreach($companies as $company)
        <option value="{{$company->id}}" {{(isset($employee->company) && $employee->company == $company->id) ? 'selected': ''}}>{{$company->name}}</option>
        @endforeach
    </select>
    @if($errors->has('company'))
        <span class="text-danger">{{ $errors->first('company') }}</span>
    @endif
</div>

resources/views/employee/create.blade.php
@extends('layout.admin')
@section('content')
    <div class="m-auto card p-2">
        <div class="card-body">
            <h5 class="card-title">Add New Employee</h5>
            <form method="post" action="{{ route('employee.store') }}" enctype="multipart/form-data">
                @csrf
                @include('employee._form')
                <div class="d-flex justify-content-between">
                    <a href="{{route('employee.index')}}" class="btn btn-secondary">Back</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/employee/edit.blade.php
@extends('layout.admin')
@section('content')
    <div class="m-auto card p-2">
        <div class="card-body">
            <h5 class="card-title">Update Employee</h5>
            <form method="post" action="{{ route('employee.update', $employee->id) }}" enctype="multipart/form-data">
                {{method_field('put')}}
                @csrf
                @include('employee._form')
                <div class="d-flex justify-content-between">
                    <a href="{{route('employee.index')}}" class="btn btn-secondary">Back</a>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/employee/index.blade.php
@extends('layout.admin')
@section('content')

    <div class="m-4">
        <div class="text-end">
            <a href="{{route('employee.create')}}" class="btn btn-primary">Add New</a>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Company</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($employees as $employee)
                <tr>
                    <td>{{$employee->first_name.' '.$employee->last_name}}</td>
                    <td>{{$employee->email}}</td>
                    <td>{{$employee->phone}}</td>
                    <td>{{$employee->myCompany->name}}</td>
                    <td>
                        <a href="{{route('employee.edit', $employee->id)}}">edit</a>
                        <button class="btn btn-link" onclick="event.preventDefault();
                            document.getElementById('employee-delete-'+{{$employee->id}}).submit();">
                            Delete
                        </button>
                        <form id="{{'employee-delete-'.$employee->id}}" action="{{route('employee.destroy', $employee->id)}}" method="post" class="d-none">
                            {{method_field('delete')}}
                            @csrf
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{$employees->links('vendor.pagination.bootstrap-4')}}
    </div>
@endsection

resources/views/layout/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{env('APP_NAME', '')}}</title>

    {{--jquery--}}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    {{--    bootstrap--}}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{{asset('css/app.css')}}" rel="stylesheet"/>
</head>
<body>
<div class="wrapper">
    <div class="header">
        @include('layout.navbar')
    </div>
    <div class="main">
        @yield('content')
    </div>
</div>
{{--bootstrap--}}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{env('APP_NAME', '')}}</title>

{{--    bootstrap--}}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{{asset('css/app.css')}}" rel="stylesheet"/>
</head>
<body>
    <div class="wrapper">
        @yield('content')
    </div>
{{--bootstrap--}}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

resources/views/layout/navbar.blade.php
<nav class="navbar navbar-dark bg-primary">
    <div class="container-fluid">
        @include('layout.sidenav')
        <div class="d-flex">
            <a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();">
                <p class="mb-0 ml-2 text-white">Logout</p>
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
    </div>
</nav>

resources/views/layout/sidenav.blade.php
<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">{{env('APP_NAME', '')}}</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item bg-primary px-2 mt-2">
                <a class="nav-link active text-black" aria-current="page" href="{{route('dashboard')}}">Home</a>
            </li>
            <li class="nav-item dropdown bg-primary px-2 mt-2">
                <a class="nav-link dropdown-toggle text-black" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Company
                </a>
                <ul class="dropdown-menu bg-primary border-none" aria-labelledby="offcanvasNavbarDropdown">
                    <li><a class="dropdown-item text-black" href="{{route('company.index')}}">List</a></li>
                    <li><a class="dropdown-item text-black" href="{{route('company.create')}}">Create</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown bg-primary px-2 mt-2">
                <a class="nav-link dropdown-toggle text-black" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Employee
                </a>
                <ul class="dropdown-menu bg-primary border-none" aria-labelledby="offcanvasNavbarDropdown">
                    <li><a class="dropdown-item text-black" href="{{route('employee.index')}}">List</a></li>
                    <li><a class="dropdown-item text-black" href="{{route('employee.create')}}">Create</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>